from datetime import timedelta

DOMAIN = "ranzenpost"
BRAND = "Ranzenpost"
ADDON_SLUG = "ranzenpost"
ADDON_REPOSITORY = "https://github.com/githuber110/ranzenpost"
DISCOVERY_SERVICE = "ranzenpost"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_TOKEN = "token"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_CHILDREN = "children"
ENTRY_VERSION = 2
LEGACY_UNIQUE_ID = DOMAIN


def unique_id_of(host, port) -> str:
    return f"{str(host).strip().lower()}:{int(port)}"

DEFAULT_PORT = 8099
DEFAULT_SCAN_INTERVAL = 60
MIN_SCAN_INTERVAL = 30
MAX_SCAN_INTERVAL = 3600
REQUEST_TIMEOUT = 15
EVENT_CACHE_TTL = timedelta(minutes=5)
UPCOMING_WINDOW_DAYS = 14
DISCOVERY_WAIT_SECONDS = 120
DISCOVERY_POLL_SECONDS = 5

KIND_LESSONS = "lessons"
KIND_EXAMS = "exams"
KIND_ABSENCES = "absences"
KIND_HOLIDAYS = "holidays"
KIND_OWN_ENTRIES = "own_entries"
CHILD_CALENDAR_KINDS = (KIND_LESSONS, KIND_EXAMS, KIND_ABSENCES)
OPT_IN_CALENDAR_KINDS = (KIND_OWN_ENTRIES,)
PURPOSE_CARD = "card"
WS_OWN_ENTRIES = f"{DOMAIN}/own_entries"
OWN_ENTRIES_MAX_DAYS = 31

MODULE_TIMETABLE = "timetable"
MODULE_LETTERS = "letters"
MODULE_PINBOARD = "pinboard"
MODULE_ABSENCES = "absences"
MODULE_CONFERENCES = "conferences"
MODULE_MESSENGER = "messenger"
MODULES = (
    MODULE_TIMETABLE,
    MODULE_LETTERS,
    MODULE_PINBOARD,
    MODULE_ABSENCES,
    MODULE_CONFERENCES,
    MODULE_MESSENGER,
)
CALENDAR_MODULES = {
    KIND_LESSONS: MODULE_TIMETABLE,
    KIND_EXAMS: MODULE_TIMETABLE,
    KIND_ABSENCES: MODULE_ABSENCES,
    KIND_OWN_ENTRIES: MODULE_TIMETABLE,
}

STATE_NONE = "none"
STATUS_OK = "ok"
STATUS_UNREACHABLE = "unreachable"
STATUS_AUTH_FAILED = "auth_failed"
CONNECTION_STATES = (STATUS_OK, "error", "unconfigured", STATUS_UNREACHABLE, STATUS_AUTH_FAILED)

LOGIN_NEEDED_ISSUE_KEY = "login_needed"
LOGIN_ISSUE_KEYS = {
    "twofactor_required_setup": "login_twofactor_setup",
    "unknown_account": "login_unknown_account",
    "default_password_blocked": "login_default_password",
    "locked": "login_locked",
    "code_step_failed": "login_code_refused",
}
NO_SCHOOL_ISSUE_KEY = "no_school_yet"
MIN_ADDON_VERSION = "2609.02.00"
UNKNOWN_VERSION = "unknown"

CHANGE_SUBSTITUTION = "substitution"
CHANGE_CANCELLATION = "cancellation"
CHANGE_KINDS = (CHANGE_SUBSTITUTION, CHANGE_CANCELLATION, "room_change", "new_lesson")

EVENT_RANZENPOST = "ranzenpost_event"
ATTR_TYPE = "type"
ATTR_ENTRY_ID = "entry_id"
ATTR_SCHOOL_ID = "school_id"
ATTR_CHILD_KEY = "child_key"
ATTR_STATUS = "status"
ATTR_PREVIOUS_STATUS = "previous_status"
ATTR_COUNT = "count"
ATTR_SENDER = "sender"
ATTR_LAST_UPDATED = "last_updated"

TRIGGER_TIMETABLE_CHANGED = "timetable_changed"
TRIGGER_LESSON_CANCELLED = "lesson_cancelled"
TRIGGER_SUBSTITUTION = "substitution"
TRIGGER_NEW_LETTER = "new_letter"
TRIGGER_NEW_POST = "new_noticeboard_post"
TRIGGER_ABSENCE_STATUS_CHANGED = "absence_status_changed"
TRIGGER_SCHOOL_UNREACHABLE = "school_unreachable"
TRIGGER_SCHOOL_REACHABLE = "school_reachable"
TRIGGER_LOGIN_NEEDED = "login_needed"
CHILD_TRIGGERS = (
    TRIGGER_TIMETABLE_CHANGED,
    TRIGGER_LESSON_CANCELLED,
    TRIGGER_SUBSTITUTION,
    TRIGGER_NEW_LETTER,
    TRIGGER_NEW_POST,
    TRIGGER_ABSENCE_STATUS_CHANGED,
)
SCHOOL_TRIGGERS = (TRIGGER_SCHOOL_UNREACHABLE, TRIGGER_SCHOOL_REACHABLE, TRIGGER_LOGIN_NEEDED)
TRIGGER_MODULES = {
    TRIGGER_TIMETABLE_CHANGED: MODULE_TIMETABLE,
    TRIGGER_LESSON_CANCELLED: MODULE_TIMETABLE,
    TRIGGER_SUBSTITUTION: MODULE_TIMETABLE,
    TRIGGER_NEW_LETTER: MODULE_LETTERS,
    TRIGGER_NEW_POST: MODULE_PINBOARD,
    TRIGGER_ABSENCE_STATUS_CHANGED: MODULE_ABSENCES,
}

CONDITION_SCHOOL_DAY = "is_school_day"
CONDITION_LESSON_RUNNING = "lesson_running"
CHILD_CONDITIONS = (CONDITION_SCHOOL_DAY, CONDITION_LESSON_RUNNING)

KEY_CURRENT_LESSON = "current_lesson"
KEY_NEXT_LESSON = "next_lesson"
KEY_SCHOOL_END_TODAY = "school_end_today"
KEY_NEXT_SCHOOL_DAY = "next_school_day"
KEY_CHANGES_TODAY = "changes_today"
KEY_UNREAD_LETTERS = "unread_letters"
KEY_UNREAD_POSTS = "unread_posts"
KEY_OPEN_ABSENCES = "open_absences"
KEY_NEXT_ABSENCE = "next_absence"
KEY_NEXT_EXAM = "next_exam"
KEY_EXAMS_UPCOMING = "exams_upcoming"
KEY_TIMETABLE_LAST_UPDATED = "timetable_last_updated"
KEY_SCHOOL_DAY_TODAY = "school_day_today"
KEY_TIMETABLE_CHANGED_TODAY = "timetable_changed_today"
KEY_TIMETABLE_CHANGED = "timetable_changed"
KEY_NEXT_HOLIDAY = "next_holiday"
KEY_NEXT_CONFERENCE = "next_conference"
KEY_CONNECTION = "connection"

ATTR_START = "start"
ATTR_END = "end"
ATTR_MINUTES_UNTIL = "minutes_until"
ATTR_MINUTES_LEFT = "minutes_left"
ATTR_CHANGES = "changes"
ATTR_LETTERS = "letters"
ATTR_POSTS = "posts"
ATTR_ABSENCES = "absences"
ATTR_EXAMS = "exams"
ATTR_DAYS = "days"
ATTR_DAYS_UNTIL = "days_until"
ATTR_TITLE = "title"
ATTR_DETAILS = "details"
ATTR_NAME = "name"
ATTR_KIND = "kind"
ATTR_SUBJECT = "subject"
ATTR_SUBJECT_CODE = "subject_code"
ATTR_SCHOOL_DAY = "school_day"
ATTR_SOURCE = "source"
ATTR_LAST_POLL = "last_poll"
ATTR_LAST_SUCCESS = "last_success"
ATTR_VERSION = "version"
ATTR_MODULES = "modules"
ATTR_FEED_PORT_OPEN = "feed_port_open"
ATTR_MODULES_DISABLED = "modules_disabled"
ATTR_INGRESS_PATH = "ingress_path"
ATTR_CHILD = "child"
ATTR_SUMMARY = "summary"
ATTR_DATE = "date"
ATTR_PERIOD = "period"

KEY_MODULES = {
    KEY_CURRENT_LESSON: MODULE_TIMETABLE,
    KEY_NEXT_LESSON: MODULE_TIMETABLE,
    KEY_SCHOOL_END_TODAY: MODULE_TIMETABLE,
    KEY_NEXT_SCHOOL_DAY: MODULE_TIMETABLE,
    KEY_NEXT_EXAM: MODULE_TIMETABLE,
    KEY_EXAMS_UPCOMING: MODULE_TIMETABLE,
    KEY_CHANGES_TODAY: MODULE_TIMETABLE,
    KEY_TIMETABLE_LAST_UPDATED: MODULE_TIMETABLE,
    KEY_SCHOOL_DAY_TODAY: MODULE_TIMETABLE,
    KEY_TIMETABLE_CHANGED_TODAY: MODULE_TIMETABLE,
    KEY_TIMETABLE_CHANGED: MODULE_TIMETABLE,
    KIND_LESSONS: MODULE_TIMETABLE,
    KIND_EXAMS: MODULE_TIMETABLE,
    KIND_ABSENCES: MODULE_ABSENCES,
    KIND_OWN_ENTRIES: MODULE_TIMETABLE,
    KEY_UNREAD_LETTERS: MODULE_LETTERS,
    KEY_UNREAD_POSTS: MODULE_PINBOARD,
    KEY_OPEN_ABSENCES: MODULE_ABSENCES,
    KEY_NEXT_ABSENCE: MODULE_ABSENCES,
    KEY_NEXT_CONFERENCE: MODULE_CONFERENCES,
}
